In [1]:
import numpy as np 
import pandas as pd
import astropy
from astropy.io import fits
import matplotlib.pyplot as plt
import scipy as sp 
import scipy.stats as sps
from scipy.stats import poisson

import seaborn as sns
plt.style.use('dark_background')
plt.rcParams['axes.facecolor'] = 'midnightblue'
plt.rcParams['figure.facecolor'] = "#060552"
plt.rcParams['axes.grid'] = 'True'
plt.rcParams['grid.color'] = 'steelblue'
plt.rcParams['grid.linewidth'] = 0.6
plt.rcParams['grid.alpha'] = 0.8
plt.rcParams['axes.edgecolor'] = 'white'
plt.rcParams['axes.linewidth'] = 0.5
plt.rcParams['legend.facecolor'] = "#060552"

# Summary Lecture 1 Notebook Component

Just initializing some random number stuff: 

In [2]:
rng = np.random.default_rng(331)
print(rng.integers(1,7,5))
print(rng.integers(1,7,5))

[1 3 5 3 6]
[2 3 2 2 6]


If you want to repeat the same random sample, you have to repeat the seed: 

In [3]:
rng = np.random.default_rng(331)
print(rng.integers(1,7,5))

[1 3 5 3 6]


Example of sampling from items in a list or array, for coin flips: 

In [4]:
rng = np.random.default_rng()  # Set up the generator with the default system seed
coin = ['h','t']
# Uses the defaults (uniform probability, replacement=True)
print("Unbiased coin: ",rng.choice(coin, size=10))
# Now specify probabilities to strongly weight towards heads:
prob = [0.9,0.1]
print("Biased coin: ",rng.choice(coin, size=10, p=prob))

Unbiased coin:  ['h' 't' 'h' 'h' 't' 'h' 't' 'h' 'h' 't']
Biased coin:  ['h' 'h' 'h' 'h' 'h' 'h' 'h' 'h' 'h' 'h']
